name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "ananttripathi1996@gmail.com"
          git config user.name "ananttripathi"
          git push https://ananttripathiak:$HF_TOKEN@huggingface.co/spaces/ananttripathiak/snip-url-backend main --force
